version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 474011752432.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=474011752432.dkr.ecr.us-east-1.amazonaws.com/music:latest
  build:
    commands:
      - docker build -t music .
      - docker tag music:latest 474011752432.dkr.ecr.us-east-1.amazonaws.com/music:latest
  post_build:
    commands:
      - docker push 474011752432.dkr.ecr.us-east-1.amazonaws.com/music:latest
      - printf '[{"name":"sa1","imageUri":"%s"}]' 6474011752432.dkr.ecr.us-east-1.amazonaws.com/music:latest > imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
    files: imagedefinitions.json
