version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 474011752432.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=474011752432.dkr.ecr.us-east-1.amazonaws.com/music:latest
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-50)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Pushing the Docker images...
      - docker build -t music .
      - docker tag music:latest 474011752432.dkr.ecr.us-east-1.amazonaws.com/music:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 474011752432.dkr.ecr.us-east-1.amazonaws.com/music:latest
      - echo Writing image definitions file...
      - printf '[{"name":"music","imageUri":"%s"}]' 474011752432.dkr.ecr.us-east-1.amazonaws.com/music:latest > imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
    files: imagedefinitions.json
